[package]
name = "injector"
version = "1.2.0"
edition = "2024"
description = "A from-scratch, standalone implementation of the Zygisk Next module."
license = "GPL-3.0-or-later"

[dependencies]
clap = { version = "4.6", default-features = false, features = [
    "std",
    "help",
    "usage",
] }
libc = "0.2"
nix = { version = "0.31", default-features = false, features = [
    "feature",
    "fs",
    "process",
    "ptrace",
    "signal",
    "socket",
    "uio",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }

[[bin]]
name = "injector"
path = "src/main.rs"

[profile.dev]
opt-level = "s"
debug = true
strip = "symbols"
panic = "unwind"
incremental = true
overflow-checks = true
lto = true

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = "symbols"
panic = "abort"
debug = "line-tables-only"
incremental = false
debug-assertions = false
overflow-checks = false
