name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_BASEDIR: "${{ github.workspace }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
        with:
          log-accepted-android-sdk-licenses: 'false'
          packages: ''

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r29-beta2
          add-to-path: true
          local-cache: ${{ github.event_name == 'push' }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 2G
          key: ${{ runner.os }}
          restore-keys: ${{ runner.os }}
          save: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Build with Gradle
        run: |
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          echo 'android.native.buildOutput=verbose' >> gradle.properties
          sed -i 's/org.gradle.unsafe.configuration-cache=true//g' gradle.properties
          ./gradlew zipRelease
          ./gradlew zipDebug

      - name: Prepare artifact
        if: success()
        id: prepareArtifact
        run: |
          releaseName=`ls module/build/outputs/release/Zygisk-Next-Next-v*-release.zip | awk -F '(/|.zip)' '{print $5}'` && echo "releaseName=$releaseName" >> $GITHUB_OUTPUT
          debugName=`ls module/build/outputs/release/Zygisk-Next-Next-v*-debug.zip | awk -F '(/|.zip)' '{print $5}'` && echo "debugName=$debugName" >> $GITHUB_OUTPUT
          unzip module/build/outputs/release/Zygisk-Next-Next-v*-release.zip -d znn-release
          unzip module/build/outputs/release/Zygisk-Next-Next-v*-debug.zip -d znn-debug

      - name: Post to channel
        if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/master' && github.ref_type != 'tag' }}
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          COMMIT_ID: ${{ github.event.head_commit.id }}
        run: |
          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            OUTPUT="module/build/outputs/release"
            export Release=$(find $OUTPUT -name "Zygisk-Next-Next-v*-release.zip")
            export Debug=$(find $OUTPUT -name "Zygisk-Next-Next-v*-debug.zip")
            URL=$(python3 .github/scripts/telegram_url.py)
            curl -v "$URL" -F Release="@$Release" -F Debug="@$Debug"
          fi

      - name: Upload release
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.prepareArtifact.outputs.releaseName }}
          path: "./znn-release/*"

      - name: Upload debug
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.prepareArtifact.outputs.debugName }}
          path: "./znn-debug/*"

